### ISSUE TITLE
这个是不是bug？

### ISSUE THREAD

**Issue by ghost** [imlzw/fastdfs#1]
roup1_storage1_1  | [2017-03-14 10:40:59] ERROR - file: fdht_client/fdht_proto.c, line: 197, connect to 172.17.0.4:11411 fail, errno: 110, error info: Connection timed out
group1_storage1_1  | [2017-03-14 10:41:29] ERROR - file: fdht_client/fdht_proto.c, line: 197, connect to 172.17.0.5:11411 fail, errno: 110, error info: Connection timed out

**Comment by ghost** [comment]
客户端测试上传文件 socket timeout

**Comment by codepython** [comment]
storage 的fdht 配置

**Comment by imlzw** [comment]
不是bug，看你是不是配置出问题。
